Fix incorrect steps in the documentation
CosmWasm/docs-deprecated-2023 pull request #177
Opened 2021-04-25 03:58 UTC by calvinaco

- Fix the git clone command as `CosmWasm/cosmwasm-examples` has updated its `master` branch directory structure
- Force `cosmwasm` to output as JSON in one of the commands for extracting information

2021-04-30 11:30 UTC, alpe requested changes
Good 👀  . Thanks for your contribution!
I did a clean checkout to test the `cd path`. Can you verify and update the PR, please?

2021-04-30 11:30 UTC, alpe commented on getting-started/compile-contract.md
> +cd cosmwasm-examples/escrow
This does not work. Steps should be
```sh
cd cosmwasm-examples
git checkout escrow-0.7.0
cd escrow
```

2021-04-30 11:30 UTC, alpe commented on getting-started/interact-with-contract.md
> +CONTRACT=$(wasmd query wasm list-contract-by-code $CODE_ID $NODE --output=json | jq -r '.[0].address')
👍  perfect. I can imagine that non json output created some trouble

2021-05-11 12:39 UTC, orkunkl commented
Applied the changes to 0.14. The branching got quite messy so had to insert the change manually, thank you

2021-05-11 12:39 UTC, closed without merging